import { Metadata } from "next";
import React from "react";

import "../globals.css";

export const metadata: Metadata = {
  title: "Gallilou Immobilier",
  description: "Generated by create next app",
  icons: [
    {
      url: "/logo.png",
      href: "/logo.png",
    },
  ],
};

function MainLayout({ children }: { children: React.ReactNode }) {
  return (
    <main>
      <div>{children}</div>
    </main>
  );
}

export default MainLayout;
